# Docker build and push API to Artifact Registry, deploy on Cloud Run 

name: Deploy Sentiment Analysis API

on:
  push:
    branches: [main]

jobs:
  login-build-push:
    name: Build, Push and Run
    runs-on: ubuntu-latest

    env:
      REGION: us-central1            
      PROJECT_ID: my-website-416300          
      REPOSITORY: website-repo
      SERVICE_ACCOUNT: site-sa
      SERVICE_NAME: sentiment_analysis_api

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - id: 'auth'
          name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with: 
            project_id: '${{ env.PROJECT_ID }}'
            credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
        
        - name: 'Docker config'
          run: |-
            gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev 

        - name: 'Build container'
          run: |-
            docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/website:${{ github.sha }}" .
          
        - name: 'Push container'
          run: |-
            docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/website:${{ github.sha }}"
        
        - name: Deploy Google Cloud Run
          run: |
            gcloud run deploy "${{ env.SERVICE_NAME }}" \
              --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/website:${{ github.sha }}" \
              --region "${{ env.REGION }}" \
              --service-account "${{ env.SERVICE_ACCOUNT }}" \
              --memory 2Gi \
              --allow-unauthenticated \
              --port 8000